# Generated by Django 4.2.1 on 2023-05-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_edicionpublicacion_imagen_nueva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edicionpublicacion',
            name='contenido_nuevo',
        ),
        migrations.RemoveField(
            model_name='edicionpublicacion',
            name='imagen_nueva',
        ),
        migrations.RemoveField(
            model_name='edicionpublicacion',
            name='titulo_nuevo',
        ),
    ]
