# Generated by Django 4.2.1 on 2023-05-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_remove_edicionpublicacion_contenido_nuevo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edicionpublicacion',
            name='editor',
        ),
        migrations.AddField(
            model_name='edicionpublicacion',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edicionpublicacion',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='edicionpublicacion',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion'),
        ),
    ]
